Pig Stack Trace
---------------
ERROR 2135: Received error from store function.null

org.apache.pig.impl.logicalLayer.FrontendException: ERROR 1066: Unable to open iterator for alias hdfs_audit
	at org.apache.pig.PigServer.openIterator(PigServer.java:912)
	at org.apache.pig.tools.grunt.GruntParser.processDump(GruntParser.java:752)
	at org.apache.pig.tools.pigscript.parser.PigScriptParser.parse(PigScriptParser.java:372)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:228)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:203)
	at org.apache.pig.tools.grunt.Grunt.run(Grunt.java:66)
	at org.apache.pig.Main.run(Main.java:542)
	at org.apache.pig.Main.main(Main.java:156)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:212)
Caused by: org.apache.pig.PigException: ERROR 1002: Unable to store alias hdfs_audit
	at org.apache.pig.PigServer.storeEx(PigServer.java:1015)
	at org.apache.pig.PigServer.store(PigServer.java:974)
	at org.apache.pig.PigServer.openIterator(PigServer.java:887)
	... 12 more
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 2135: Received error from store function.null
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POStore.getNextTuple(POStore.java:167)
	at org.apache.pig.backend.hadoop.executionengine.fetch.FetchLauncher.runPipeline(FetchLauncher.java:160)
	at org.apache.pig.backend.hadoop.executionengine.fetch.FetchLauncher.launchPig(FetchLauncher.java:81)
	at org.apache.pig.backend.hadoop.executionengine.HExecutionEngine.launchPig(HExecutionEngine.java:275)
	at org.apache.pig.PigServer.launchPlan(PigServer.java:1367)
	at org.apache.pig.PigServer.executeCompiledLogicalPlan(PigServer.java:1352)
	at org.apache.pig.PigServer.storeEx(PigServer.java:1011)
	... 14 more
Caused by: java.nio.channels.ClosedChannelException
	at org.apache.hadoop.hdfs.DFSOutputStream.checkClosed(DFSOutputStream.java:1317)
	at org.apache.hadoop.fs.FSOutputSummer.write(FSOutputSummer.java:98)
	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.write(FSDataOutputStream.java:59)
	at java.io.DataOutputStream.write(DataOutputStream.java:90)
	at java.io.DataOutputStream.writeUTF(DataOutputStream.java:384)
	at java.io.DataOutputStream.writeUTF(DataOutputStream.java:306)
	at org.apache.pig.data.utils.SedesHelper.writeChararray(SedesHelper.java:66)
	at org.apache.pig.data.BinInterSedes.writeDatum(BinInterSedes.java:580)
	at org.apache.pig.data.BinInterSedes.writeDatum(BinInterSedes.java:462)
	at org.apache.pig.data.utils.SedesHelper.writeGenericTuple(SedesHelper.java:135)
	at org.apache.pig.data.BinInterSedes.writeTuple(BinInterSedes.java:650)
	at org.apache.pig.data.BinInterSedes.writeDatum(BinInterSedes.java:470)
	at org.apache.pig.data.BinInterSedes.writeDatum(BinInterSedes.java:462)
	at org.apache.pig.impl.io.InterRecordWriter.write(InterRecordWriter.java:73)
	at org.apache.pig.impl.io.InterStorage.putNext(InterStorage.java:88)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.POStore.getNextTuple(POStore.java:148)
	... 20 more
================================================================================
